// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/3/25 16:10:28
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/media/domi/Data/project/web/site/azo-crafts-page/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/media/domi/Data/project/web/site/azo-crafts-page/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/media/domi/Data/project/web/site/azo-crafts-page/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/media/domi/Data/project/web/site/azo-crafts-page/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/media/domi/Data/project/web/site/azo-crafts-page/app/plugins/**/*.{js,ts,mjs}","/media/domi/Data/project/web/site/azo-crafts-page/app/composables/**/*.{js,ts,mjs}","/media/domi/Data/project/web/site/azo-crafts-page/app/utils/**/*.{js,ts,mjs}","/media/domi/Data/project/web/site/azo-crafts-page/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/media/domi/Data/project/web/site/azo-crafts-page/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/media/domi/Data/project/web/site/azo-crafts-page/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/media/domi/Data/project/web/site/azo-crafts-page/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;